### ISSUE TITLE
Cache lifetime / expiry date required

### ISSUE THREAD

**Issue by pmamat** [ArtemFitiskin/jquery-autocompleter#10]
Thanks for your great autocompleter plugin!

I'm only missing a lifetime setting / expiry date for the cached data. Even when querying a regularly changing database a ("short", e. g. 1 day) cache time would be greatly appreciated. But when searching again the other day, from my point of view the server should be called.

**Comment by ArtemFitiskin** [comment]
@pmamat thank for your idea. Try to use new option called **cacheExpires** in 0.1.9.3

**Comment by pmamat** [comment]
@ArtemFitiskin Thanks a lot for the fast implementation. 

Is there a reason you did not add the new option to the "allowOptions" array? 
If my test worked correctly, one cannot change the default value at the moment.

**Comment by ArtemFitiskin** [comment]
Oops, I think that's a mistake.

**Comment by pmamat** [comment]
@ArtemFitiskin 
Great, thanks again for your quick response!
