### ISSUE TITLE
[Request] CSS and width control

### ISSUE THREAD

**Issue by badulesia** [ArtemFitiskin/jquery-autocompleter#28]
Hello.
Interesting plugin, light and effective.
I have two requests.
- CSS
the CSS file included is not complete and can't render the plugin correctly at first use. I was able to obtain something correct by copying the Crayola colors CSS used in your demo. Can you provide this CSS as the default one ?
- width control
in CSS, width is set to 100%, that means that it will enlarge as much as the parent element. Can you code some kind of width control for the list ? Interesting widths would be the same as the input, a fixed width (px, em ...), fit to the answers. Actually I need to set a width to a parent <div> to obtain this. This is not convinient.

Thank you.
best regards.

**Comment by ArtemFitiskin** [comment]
Thanks @badulesia 

For a long time I did not follow the repository (my bad) and now, I see that it needs some fundamental changes, which will breaks backward compatible.

The problem that you are talking about lives deep and, in my opinion, can not be properly solved by simple revision of the styles.

Anyway, I've made a working example for you on the JSFiddle, which I hope will help: [https://jsfiddle.net/fitiskin/s3Lt00r7/](https://jsfiddle.net/fitiskin/s3Lt00r7/).

As you can see this solution is based on wrapper with fixed width and relative position:

```css
.field {
  width: 200px;
  position: relative;
} 

.field input, 
.field .autocompleter {
  width: 100%;
}
```

```html
<div class="field">
  <input type="text" name="name" id="name">
</div>
```

If this solution does not work for you, please let me know.
